[project]
name = "comfyrest_studies01"
version = "0.1.0"
description = "Explore ComfyUI's REST API"
requires-python = ">=3.10"

[tool.pytest]
addopts = "-q"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
